### ISSUE TITLE
dotnet new angularjs installs Angular (not AngularJS) app

### ISSUE THREAD

**Issue by dotfo** [idea42co/NetCoreTemplates#3]
When creating a new project using the template angularjs, the app that is being installed is an Angular v6 app, not AngularJS.

**Comment by ryan-idea42** [comment]
Good catch.

The older version had AngularJS (which I was calling Angular 1), but since it's not something people should be starting projects with anymore, I deleted it from the packages and built the new Angular with Angular 6. I just left the template info untouched. 

Let me correct this now and release the package to NuGet.

**Comment by dotfo** [comment]
Well actually AngularJS 1.7.x LTS will be released this month, because so many projects still rely on that framework, and sadly I am on such a project, wich really would benefit to start on a new boilerplate code such as yours, therefore I hoped you would update your angularjs template to include that ;-)

https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c

**Comment by ryan-idea42** [comment]
@dotfo Try this out and see if this works for you.
 
[Idea42.NetCore.Templates.1.0.94.nupkg.zip](https://github.com/idea42co/NetCoreTemplates/files/2155701/Idea42.NetCore.Templates.1.0.94.nupkg.zip)

Unzip this, then you can install it by using similar commands as before:

```
dotnet new -i Idea42.NetCore.Templates.1.0.94.nupkg
```

If it works, you can uninstall this and download the real one from NuGet by running: 

```
dotnet new -u Idea42.NetCore.Templates.1.0.94
```

Either way, this works on my local runs. I'll push later on tonight.

**Comment by ryan-idea42** [comment]
Change has been deployed to NuGet. I would give it an hour or two before trying to install from NuGet using: 

```
dotnet new --install Idea42.NetCore.Templates::*
```

Hopefully, this helps you out in your endeavors! And do please let us know if you have any issues and we'll do our best to help. :-)

**Comment by dotfo** [comment]
This is just what I needed :)
